Bookstore - Add styling to website
guerreiropedr0/bookstore pull request #4
Opened 2022-02-22 20:23 UTC by guerreiropedr0

In this pull request, I added styling to the project.

2022-02-22 23:19 UTC, BrianSammit requested changes
# CHANGES REQUIRED 🔴 🛑
Hello @guerreiropedr0, great job you are doing so far in this project. 💯

TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 
- Great job working on the styles I like your design.

However, there are a few changes to make to move to the next project 🛠️ . Keep working hard 💪 💻 

## Required Changes ♻️

- [ ] It would be better if your design  is EXACTLY the same as the one provided on [Zeplin](https://zeplin.io/)

Currently, your design is totally different from the given design. Please make sure you follow the design. 💪 😄 

Please make these required changes and send it again for another review 👍 💪
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
# HAPPY CODING!!! 😄 

![cat](https://user-images.githubusercontent.com/64173189/131593916-14c184cb-b5af-40f7-8fba-779155f154cb.gif)


**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

--------

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-23 08:08 UTC, guerreiropedr0 commented
Hi, I don't think I have to change the colors, only the layout, which is similar already right?

2022-02-23 08:39 UTC, Rustamxon7 requested changes
## STATUS: CHANGES REQUIRED 🟡
 Hi @guerreiropedr0  ,
 
 Great work on making the changes requested by the previous reviewer, but there are still some which aren't addressed yet.
 
 ## Required Changes ♻️
 _Check the comments under the review._
 
 ![really close](https://camo.githubusercontent.com/610ba39845cbc5bfce08f092117aa5573447b79bd89160db59ada95582b1836c/68747470733a2f2f632e74656e6f722e636f6d2f66754b6a7462743762344541414141642f7265616c6c792d7265616c6c792d636c6f73652d62696c6c2d6d75727261792e676966)
 
 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-23 08:39 UTC, Rustamxon7 commented on src/index.css
>  :root {
- [ ] As the previous reviewer suggested everything should be EXACTLY the same as the one provided on [Zeplin](https://zeplin.io/) including colors, font family, spacing, lines. Please kindly change the design as in the original. Because in this part of the project you will learn to create the website from the provided design, and Zaplin is easy to tool for developers for this 👌✅

2022-02-23 14:26 UTC, FrederickMih approved these changes
# Approved :heavy_check_mark: 

#### Hi @guerreiropedr0 , 


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-23 14:26 UTC, FrederickMih commented on src/components/Navbar.js
> -        <BsPerson className="user-icon" />
- Please make sure that the user-icon should be in line with the main container. Check once more the original design.

2022-02-23 14:26 UTC, FrederickMih commented on src/components/Navbar.js
>      <h1 className="title">Bookstore CMS</h1>
- lets the logo be on a horizontal line like the original design. It should not be split into two

2022-02-23 14:47 UTC, guerreiropedr0 commented on src/components/Navbar.js
>      <h1 className="title">Bookstore CMS</h1>
Hi, it is on a horizontal line Frederick
![image](https://user-images.githubusercontent.com/78462401/155342686-79d2d3a3-2874-4589-9075-46b541c8b173.png)

2022-02-23 14:47 UTC, guerreiropedr0 commented on src/components/Navbar.js
> -        <BsPerson className="user-icon" />
Hi Frederick, it is in line with the main container
![image](https://user-images.githubusercontent.com/78462401/155342876-52fe2799-a7d6-46a2-9ce7-a9ebb4bfd3b7.png)

2022-02-23 15:48 UTC, merged